driver_name=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://192.168.0.100:3306/axloth_member_center?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&allowPublicKeyRetrieval=true
username=Reiscark
password=1357924680